image:
  file: .gitpod.Dockerfile

tasks:
  - name: Styleguide
    init: echo "Awaiting NPM install..." && while ! find ./.gitpod.lock 2> /dev/null 1> /dev/null; do sleep 5; done
    command: npm run start:gitpod:styleguide
    openIn: bottom
    openMode: tab-after
  - name: Unit Tests
    init: echo "Awaiting NPM install..." && while ! find ./.gitpod.lock 2> /dev/null 1> /dev/null; do sleep 5; done
    command: npm run tdd:unit
    openIn: right
    openMode: tab-after
  - name: E2E Tests
    init: echo "Awaiting NPM install..." && while ! find ./.gitpod.lock 2> /dev/null 1> /dev/null; do sleep 5; done
    command: npm run tdd:e2e
    openIn: right
    openMode: split-right
  - name: Api
    init: rm -rf ./.gitpod.lock && npm install && touch ./.gitpod.lock
    command: HELLO=world
      FETCHQ_CORS_ENABLED=true
      FETCHQ_CORS_ORIGIN=$(gp url 3000)
      npm run start:gitpod:api
    openIn: bottom
    openMode: tab-after
  - name: App
    init: echo "Awaiting NPM install..." && while ! find ./.gitpod.lock 2> /dev/null 1> /dev/null; do sleep 5; done
    command: npm run start:gitpod:app
    openIn: bottom
    openMode: split-right

# ports:
#   - port: 5432
#     onOpen: ignore
#   - port: 8008
#     onOpen: ignore
#   - port: 8080
#     onOpen: ignore
#   - port: 3000
#     onOpen: ignore
#   - port: 6060
#     onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.1:DO6k4GCpqhwZcKo+jY9xjQ==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - mikestead.dotenv@1.0.1:SSXjr5hZcbqSF7nMIhTNnA==
    - wayou.vscode-todo-highlight@1.0.4:8IqxuxCVol2WnScJc5xVzg==
