export const f1 = {
  items: [
    {
      id: 1,
      name: 'q1',
      is_active: true,
      current_version: 0,
      max_attempts: 5,
      logs_retention: '24h',
      created_at: '2021-02-28T10:09:48.926Z',
      cnt: 0,
      pnd: 0,
      pln: 0,
      act: 0,
      cpl: 0,
      kll: 0,
      drp: 0,
      pkd: 0,
      prc: 0,
      res: 0,
      orp: 0,
      err: 0,
    },
    {
      id: 2,
      name: 'q2',
      is_active: false,
      current_version: 1,
      max_attempts: 3,
      logs_retention: '12h',
      created_at: '2021-01-28T10:09:48.926Z',
      cnt: 0,
      pnd: 0,
      pln: 0,
      act: 0,
      cpl: 0,
      kll: 0,
      drp: 0,
      pkd: 0,
      prc: 0,
      res: 0,
      orp: 0,
      err: 0,
    },
  ],
};
